// const sqlite3 = require("better-sqlite3");
// const db = new sqlite3("database.db");

const Database = require("better-sqlite3");
const db = new Database("database.db", { verbose: console.log });

function insertSampleData() {
  const students = [
    {
      admission_no: "A001",
      name: "John Doe",
      address: "123 Main St, Springfield",
      date_of_birth: "2005-05-15",
      date_of_admission: "2020-06-01",
      class: "10",
      aadhar_no: "1234-5678-9012",
      is_cwsn: 0,
      father_name: "Michael Doe",
      father_contact: "9876543210",
      mother_name: "Jane Doe",
      mother_contact: "9876543211",
      is_hostler: 0,
      guardian_name: "Emily Doe",
      guardian_address: "123 Main St, Springfield",
      guardian_contact: "9876543212",
      alternate_contact: "9876543213",
      email: "john.doe@example.com",
      identification_marks: "None",
      bank_name: "ABC Bank",
      branch_name: "Springfield",
      ifsc_code: "ABCD1234567",
      account_no: "123456789012",
      religion_caste: "Christian",
      category: "General",
      father_qualification: "Graduate",
      father_occupation: "Engineer",
      mother_qualification: "Postgraduate",
      mother_occupation: "Teacher",
      annual_income: 500000,
      height: 5.8,
      weight: 60,
      blood_group: "O+",
      special_diseases: "None",
      vaccination_details: "Fully vaccinated",
    },
    {
      admission_no: "A002",
      name: "Alice Smith",
      address: "456 Elm St, Springfield",
      date_of_birth: "2006-07-20",
      date_of_admission: "2021-06-01",
      class: "9",
      aadhar_no: "2345-6789-0123",
      is_cwsn: 1,
      father_name: "Robert Smith",
      father_contact: "9876543214",
      mother_name: "Linda Smith",
      mother_contact: "9876543215",
      is_hostler: 1,
      guardian_name: "Sarah Smith",
      guardian_address: "456 Elm St, Springfield",
      guardian_contact: "9876543216",
      alternate_contact: "9876543217",
      email: "alice.smith@example.com",
      identification_marks: "Freckles",
      bank_name: "XYZ Bank",
      branch_name: "Springfield",
      ifsc_code: "XYZ1234567",
      account_no: "234567890123",
      religion_caste: "Hindu",
      category: "OBC",
      father_qualification: "Postgraduate",
      father_occupation: "Doctor",
      mother_qualification: "Graduate",
      mother_occupation: "Nurse",
      annual_income: 600000,
      height: 5.5,
      weight: 55,
      blood_group: "A+",
      special_diseases: "None",
      vaccination_details: "Fully vaccinated",
    },
    {
      admission_no: "A003",
      name: "Bob Johnson",
      address: "789 Oak St, Springfield",
      date_of_birth: "2007-08-25",
      date_of_admission: "2022-06-01",
      class: "8",
      aadhar_no: "3456-7890-1234",
      is_cwsn: 0,
      father_name: "James Johnson",
      father_contact: "9876543218",
      mother_name: "Patricia Johnson",
      mother_contact: "9876543219",
      is_hostler: 0,
      guardian_name: "Michael Johnson",
      guardian_address: "789 Oak St, Springfield",
      guardian_contact: "9876543220",
      alternate_contact: "9876543221",
      email: "bob.johnson@example.com",
      identification_marks: "Scar on left arm",
      bank_name: "LMN Bank",
      branch_name: "Springfield",
      ifsc_code: "LMN1234567",
      account_no: "345678901234",
      religion_caste: "Christian",
      category: "General",
      father_qualification: "Graduate",
      father_occupation: "Businessman",
      mother_qualification: "Graduate",
      mother_occupation: "Housewife",
      annual_income: 700000,
      height: 5.6,
      weight: 65,
      blood_group: "B+",
      special_diseases: "None",
      vaccination_details: "Fully vaccinated",
    },
    {
      admission_no: "A004",
      name: "Charlie Brown",
      address: "321 Pine St, Springfield",
      date_of_birth: "2008-09-30",
      date_of_admission: "2023-06-01",
      class: "7",
      aadhar_no: "4567-8901-2345",
      is_cwsn: 1,
      father_name: "Charles Brown",
      father_contact: "9876543222",
      mother_name: "Lucy Brown",
      mother_contact: "9876543223",
      is_hostler: 1,
      guardian_name: "Sally Brown",
      guardian_address: "321 Pine St, Springfield",
      guardian_contact: "9876543224",
      alternate_contact: "9876543225",
      email: "charlie.brown@example.com",
      identification_marks: "None",
      bank_name: "OPQ Bank",
      branch_name: "Springfield",
      ifsc_code: "OPQ1234567",
      account_no: "456789012345",
      religion_caste: "Hindu",
      category: "SC",
      father_qualification: "Postgraduate",
      father_occupation: "Teacher",
      mother_qualification: "Graduate",
      mother_occupation: "Engineer",
      annual_income: 400000,
      height: 5.4,
      weight: 50,
      blood_group: "AB+",
      special_diseases: "None",
      vaccination_details: "Fully vaccinated",
    },
    {
      admission_no: "A005",
      name: "Daisy Miller",
      address: "654 Maple St, Springfield",
      date_of_birth: "2009-10-12",
      date_of_admission: "2024-06-01",
      class: "6",
      aadhar_no: "5678-9012-3456",
      is_cwsn: 0,
      father_name: "David Miller",
      father_contact: "9876543226",
      mother_name: "Emma Miller",
      mother_contact: "9876543227",
      is_hostler: 0,
      guardian_name: "Olivia Miller",
      guardian_address: "654 Maple St, Springfield",
      guardian_contact: "9876543228",
      alternate_contact: "9876543229",
      email: "daisy.miller@example.com",
      identification_marks: "Mole on right cheek",
      bank_name: "RST Bank",
      branch_name: "Springfield",
      ifsc_code: "RST1234567",
      account_no: "567890123456",
      religion_caste: "Christian",
      category: "General",
      father_qualification: "Graduate",
      father_occupation: "Lawyer",
      mother_qualification: "Postgraduate",
      mother_occupation: "Doctor",
      annual_income: 800000,
      height: 5.7,
      weight: 58,
      blood_group: "O-",
      special_diseases: "None",
      vaccination_details: "Fully vaccinated",
    },
  ];

  const insertStmt = db.prepare(`
    INSERT INTO students (
      admission_no, name, address, date_of_birth, date_of_admission, class, aadhar_no, is_cwsn,
      father_name, father_contact, mother_name, mother_contact, is_hostler, guardian_name,
      guardian_address, guardian_contact, alternate_contact, email, identification_marks,
      bank_name, branch_name, ifsc_code, account_no, religion_caste, category,
      father_qualification, father_occupation, mother_qualification, mother_occupation,
      annual_income, height, weight, blood_group, special_diseases, vaccination_details
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  db.transaction(() => {
    for (const student of students) {
      insertStmt.run(
        student.admission_no,
        student.name,
        student.address,
        student.date_of_birth,
        student.date_of_admission,
        student.class,
        student.aadhar_no,
        student.is_cwsn,
        student.father_name,
        student.father_contact,
        student.mother_name,
        student.mother_contact,
        student.is_hostler,
        student.guardian_name,
        student.guardian_address,
        student.guardian_contact,
        student.alternate_contact,
        student.email,
        student.identification_marks,
        student.bank_name,
        student.branch_name,
        student.ifsc_code,
        student.account_no,
        student.religion_caste,
        student.category,
        student.father_qualification,
        student.father_occupation,
        student.mother_qualification,
        student.mother_occupation,
        student.annual_income,
        student.height,
        student.weight,
        student.blood_group,
        student.special_diseases,
        student.vaccination_details
      );
    }
  })();

  console.log("Sample data inserted successfully.");
}

// Call the function to insert sample data
insertSampleData();
